### ISSUE TITLE
'Copy [XMP] form selected images' include <SPACE> in 1st char

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#38]
Hi,

When I copy any metadata from the image, an empty character is included 
this bug (?) don't affect exif data in image

[see sample tif in zip file and screenshot]

![ScreenShot 2020-07-26 a la(s) 01 15 12](https://user-images.githubusercontent.com/693328/88471334-b7cdc980-cede-11ea-9158-3e16af949856.jpg)

[AR-CIFHA-CDV-AS-4-165.tif.zip](https://github.com/hvdwolf/jExifToolGUI/files/4977131/AR-CIFHA-CDV-AS-4-165.tif.zip)

best,
Martin
OSX 10.15.5
jExifToolGUI 1.4.0
openjdk version "11.0.8" 2020-07-14

**Comment by hvdwolf** [comment]
Fixed in 1.4.1 (also for GPano)

**Comment by Saijin-Naib** [comment]
![image](https://user-images.githubusercontent.com/19295950/94727505-d57b3d00-032c-11eb-9a0e-45e7478e3a86.png)
Still seeing this behavior under jExifToolGUI V1.6.1 with exiftool 12.0.6.0, as you can see in fields Focal Length and Focal Length in 35mm Format, when used against Lossless Compressed Fujifilm RAFs coming out of an X-T2 with firmware 4.32

**Comment by hvdwolf** [comment]
Confirmed. I need to do some "tricks" with these two fields and these fields are not correctly "trimmed".

Will be solved in minor release 1.6.2 (in a few days).
